### ISSUE TITLE
Possibility of translation

### ISSUE THREAD

**Issue by michag86** [nickbooties/owncloud-PasswordPolicy2#1]
Can you please modify the app that it is possible to contribute translations?

How to do this is written here:
https://doc.owncloud.org/server/8.0/developer_manual/app/l10n.html

The number of strings is small and I would like to contribute a German translation.

**Comment by nickbooties** [comment]
Thanks, yes this is something I would like to do in the near future.

**Comment by michag86** [comment]
I think it's far everything implemented. Maybe there are a few parts of the text that could be better formulated.
