### ISSUE TITLE
Passwort Policy not working in ownCloud 9.0.0

### ISSUE THREAD

**Issue by michag86** [nickbooties/owncloud-PasswordPolicy2#15]
Password Policy is not working in ownCloud 9.0.0 because of this error:
`{"reqId":"mBUM+gmIN7kbU1w3HEF4","remoteAddr":"192.168.234.20","app":"PHP","message":"Call to undefined method OC_L10N::get() at \/var\/www\/owncloud\/apps\/passwordpolicy\/controller\/passwordpolicycontroller.php#27","level":3,"time":"2016-03-12T12:15:49+00:00"}`

I'm working on this...

**Comment by pangol16** [comment]
I tested the new version with my owncloud 9. It works good like before.
Thanks for the quick fix.

Martin

**Comment by michag86** [comment]
Also successfully tested on ownCloud 8.1.5
