### ISSUE TITLE
Apply password policy on user creation

### ISSUE THREAD

**Issue by michag86** [nickbooties/owncloud-PasswordPolicy2#17]
If a user is created, the password policy is not applied.
It is required to create a hook on "preCreateUser".

I will work on this...

**Comment by quenenni** [comment]
Hello michag86,

That's exactly the plugin I was looking for.. Thanks a lot.
I tested it on a v9.02 and it works well.

Any news on this feature? 

Cheers

**Comment by michag86** [comment]
@quenenni I've created a pull request #18 for this feature.
Ask @nickbooties for merging this.

**Comment by quenenni** [comment]
I applied your changes directly into my code to test it.

It works. I can't create a user from the Users page with a weak password.
The only problem is that the error msg that appears on top of the page is wrong:

```
Erreur a la création d'un utilisateur : {message}
```

The first part is correct, but it seems the part about the reason of the failure ({message}) is not correctly managed.

Ps: I tested it on an owncloud v9.1
