### ISSUE TITLE
Problems when trying to reset Password

### ISSUE THREAD

**Issue by benedikt-buchert** [nickbooties/owncloud-PasswordPolicy2#21]
I get cloudn't reset password because the token is expired. When I switch the password policy app off it works.

**Comment by michag86** [comment]
What ownCloud version?
Any message in the ownCloud log?

**Comment by benedikt-buchert** [comment]
ownCloud 9.0.2 (production)

Log: Illegal string offset 'sharekey' at /usr/share/webapps/owncloud/apps/passwords/service/passwordservice.php#47

**Comment by michag86** [comment]
This error is generated by the passwords app and not the passwordpolicy app.
What way of password reset do you mean?
- lost password function
- change password in personal settings
- change password in user management

Does the error appear if you disable passwords and enable passwordpolicy?

**Comment by benedikt-buchert** [comment]
It was the lost passwords function

When I dissabled and enabled the app it worked again. I guess you can close this.
